/* eslint-disable */
// Generated by scripts/generate-cloud-route-manifest.mjs. Do not edit by hand.
import type { NextRequest } from "next/server";
import * as route012 from "@/app/api/agents/config/mcp-catalog/microsoft/login/route";
import * as route013 from "@/app/api/agents/config/mcp-catalog/oauth/login/route";
import * as route010 from "@/app/api/agents/config/mcp-catalog/connect/route";
import * as route011 from "@/app/api/agents/config/mcp-catalog/discord-check/route";
import * as route015 from "@/app/api/agents/config/mcp-catalog/test/route";
import * as route016 from "@/app/api/agents/config/mcp-catalog/verify/route";
import * as route017 from "@/app/api/agents/config/notifications/test/route";
import * as route019 from "@/app/api/agents/conversations/[id]/actions/route";
import * as route020 from "@/app/api/agents/conversations/[id]/claude-transcript/route";
import * as route021 from "@/app/api/agents/conversations/[id]/compact/route";
import * as route022 from "@/app/api/agents/conversations/[id]/continue/route";
import * as route023 from "@/app/api/agents/conversations/[id]/diffs/route";
import * as route024 from "@/app/api/agents/conversations/[id]/events-log/route";
import * as route025 from "@/app/api/agents/conversations/[id]/events/route";
import * as route035 from "@/app/api/agents/library/[slug]/add/route";
import * as route037 from "@/app/api/agents/personas/[slug]/avatar/route";
import * as route038 from "@/app/api/agents/personas/[slug]/export/route";
import * as route040 from "@/app/api/agents/personas/[slug]/workspace/route";
import * as route042 from "@/app/api/agents/providers/[id]/models/route";
import * as route043 from "@/app/api/agents/providers/[id]/verify/route";
import * as route049 from "@/app/api/agents/skills/[key]/bundle-into-cabinet/route";
import * as route069 from "@/app/api/daemon/session/[id]/output/route";
import * as route006 from "@/app/api/agents/config/cabinet-env/route";
import * as route007 from "@/app/api/agents/config/cli-mcp-servers/route";
import * as route008 from "@/app/api/agents/config/integration-environments/route";
import * as route009 from "@/app/api/agents/config/integrations/route";
import * as route014 from "@/app/api/agents/config/mcp-catalog/route";
import * as route027 from "@/app/api/agents/conversations/events/route";
import * as route045 from "@/app/api/agents/providers/status/route";
import * as route051 from "@/app/api/agents/skills/catalog/route";
import * as route052 from "@/app/api/agents/skills/import/route";
import * as route054 from "@/app/api/agents/skills/scan/route";
import * as route100 from "@/app/api/kb/pages/meta/route";
import * as route120 from "@/app/api/system/diagnostics/export/route";
import * as route121 from "@/app/api/system/diagnostics/log-tail/route";
import * as route137 from "@/app/api/system/update/apply/route";
import * as route139 from "@/app/api/system/update/status/route";
import * as route000 from "@/app/api/agents/[id]/jobs/[jobId]/route";
import * as route001 from "@/app/api/agents/[id]/jobs/route";
import * as route005 from "@/app/api/agents/claude-login/[action]/route";
import * as route026 from "@/app/api/agents/conversations/[id]/route";
import * as route039 from "@/app/api/agents/personas/[slug]/route";
import * as route050 from "@/app/api/agents/skills/[key]/route";
import * as route065 from "@/app/api/chat/channels/[slug]/route";
import * as route074 from "@/app/api/git/diff/[hash]/route";
import * as route084 from "@/app/api/gmail/thread/[id]/route";
import * as route086 from "@/app/api/google-drive/mounts/[id]/route";
import * as route003 from "@/app/api/agents/auto-link/route";
import * as route004 from "@/app/api/agents/channels/route";
import * as route018 from "@/app/api/agents/config/route";
import * as route028 from "@/app/api/agents/conversations/route";
import * as route029 from "@/app/api/agents/digest/route";
import * as route030 from "@/app/api/agents/events/route";
import * as route031 from "@/app/api/agents/gallery/route";
import * as route032 from "@/app/api/agents/headless/route";
import * as route033 from "@/app/api/agents/import/route";
import * as route034 from "@/app/api/agents/inbox-drafts/route";
import * as route036 from "@/app/api/agents/library/route";
import * as route041 from "@/app/api/agents/personas/route";
import * as route044 from "@/app/api/agents/providers/route";
import * as route046 from "@/app/api/agents/review/route";
import * as route048 from "@/app/api/agents/scheduler/route";
import * as route053 from "@/app/api/agents/skills/route";
import * as route055 from "@/app/api/agents/tasks/route";
import * as route056 from "@/app/api/ai/render-md/route";
import * as route058 from "@/app/api/auth/check/route";
import * as route059 from "@/app/api/auth/login/route";
import * as route060 from "@/app/api/browser/bookmarks/route";
import * as route061 from "@/app/api/browser/frame-check/route";
import * as route062 from "@/app/api/cabinets/classify/route";
import * as route063 from "@/app/api/cabinets/create/route";
import * as route064 from "@/app/api/cabinets/overview/route";
import * as route066 from "@/app/api/chat/channels/route";
import * as route067 from "@/app/api/cloud/status/route";
import * as route068 from "@/app/api/daemon/auth/route";
import * as route070 from "@/app/api/daemon/sessions/route";
import * as route073 from "@/app/api/git/commit/route";
import * as route076 from "@/app/api/git/pull/route";
import * as route077 from "@/app/api/git/restore/route";
import * as route078 from "@/app/api/github/repo/route";
import * as route079 from "@/app/api/gmail/connect/route";
import * as route080 from "@/app/api/gmail/disconnect/route";
import * as route081 from "@/app/api/gmail/index/route";
import * as route082 from "@/app/api/gmail/search/route";
import * as route083 from "@/app/api/gmail/status/route";
import * as route085 from "@/app/api/google-drive/browse/route";
import * as route087 from "@/app/api/google-drive/mounts/route";
import * as route088 from "@/app/api/google-drive/reveal/route";
import * as route089 from "@/app/api/google-drive/serve/route";
import * as route090 from "@/app/api/google-drive/status/route";
import * as route091 from "@/app/api/google-drive/tree/route";
import * as route092 from "@/app/api/health/daemon/route";
import * as route094 from "@/app/api/history/activity/route";
import * as route095 from "@/app/api/history/compact/route";
import * as route096 from "@/app/api/history/config/route";
import * as route097 from "@/app/api/history/diff/route";
import * as route098 from "@/app/api/history/file/route";
import * as route099 from "@/app/api/jobs/library/route";
import * as route101 from "@/app/api/knowledge-sources/connect-inline/route";
import * as route102 from "@/app/api/knowledge-sources/scan/route";
import * as route103 from "@/app/api/onboarding/setup/route";
import * as route106 from "@/app/api/references/undo/route";
import * as route108 from "@/app/api/registry/import/route";
import * as route110 from "@/app/api/rooms/active/route";
import * as route112 from "@/app/api/schedule/parse/route";
import * as route114 from "@/app/api/system/audit-log/route";
import * as route115 from "@/app/api/system/backup/route";
import * as route116 from "@/app/api/system/cabinet-manifest/route";
import * as route117 from "@/app/api/system/client-log/route";
import * as route118 from "@/app/api/system/create-file/route";
import * as route119 from "@/app/api/system/data-dir/route";
import * as route122 from "@/app/api/system/diagnostics/route";
import * as route123 from "@/app/api/system/feedback/route";
import * as route124 from "@/app/api/system/file-settings/route";
import * as route125 from "@/app/api/system/import-apple-notes/route";
import * as route126 from "@/app/api/system/import-folder/route";
import * as route127 from "@/app/api/system/import-notion/route";
import * as route128 from "@/app/api/system/integration-requests/route";
import * as route129 from "@/app/api/system/link-repo/route";
import * as route130 from "@/app/api/system/open-data-dir/route";
import * as route131 from "@/app/api/system/open-path/route";
import * as route132 from "@/app/api/system/pick-directory/route";
import * as route133 from "@/app/api/system/pick-file/route";
import * as route134 from "@/app/api/system/restart/route";
import * as route135 from "@/app/api/system/reveal/route";
import * as route136 from "@/app/api/system/symlink/route";
import * as route138 from "@/app/api/system/update/route";
import * as route141 from "@/app/api/telemetry/settings/route";
import * as route142 from "@/app/api/terminal/open/route";
import * as route145 from "@/app/api/user/avatar/route";
import * as route146 from "@/app/api/user/profile/route";
import * as route075 from "@/app/api/git/log/[...path]/route";
import * as route002 from "@/app/api/agents/[id]/route";
import * as route107 from "@/app/api/registry/[slug]/route";
import * as route047 from "@/app/api/agents/route";
import * as route071 from "@/app/api/data-locations/route";
import * as route072 from "@/app/api/disclaimer/route";
import * as route093 from "@/app/api/health/route";
import * as route105 from "@/app/api/pages/route";
import * as route109 from "@/app/api/registry/route";
import * as route111 from "@/app/api/rooms/route";
import * as route113 from "@/app/api/search/route";
import * as route140 from "@/app/api/telemetry/route";
import * as route143 from "@/app/api/tree/route";
import * as route057 from "@/app/api/assets/[...path]/route";
import * as route104 from "@/app/api/pages/[...path]/route";
import * as route144 from "@/app/api/upload/[...path]/route";

export type CloudRouteMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";
export type CloudRouteHandler = (
  request: NextRequest,
  context: { params: Promise<Record<string, string | string[]>> }
) => Response | Promise<Response>;
export type CloudRouteModule = Partial<Record<CloudRouteMethod, CloudRouteHandler>>;

interface CloudRouteEntry {
  pathname: string;
  pattern: RegExp;
  params: Array<{ name: string; catchAll: boolean; optional: boolean }>;
  module: CloudRouteModule;
}

const routes: CloudRouteEntry[] = [
  {
    pathname: "/api/agents/config/mcp-catalog/microsoft/login",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/microsoft/login/?$"),
    params: [],
    module: route012 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog/oauth/login",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/oauth/login/?$"),
    params: [],
    module: route013 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog/connect",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/connect/?$"),
    params: [],
    module: route010 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog/discord-check",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/discord-check/?$"),
    params: [],
    module: route011 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog/test",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/test/?$"),
    params: [],
    module: route015 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog/verify",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/verify/?$"),
    params: [],
    module: route016 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/notifications/test",
    pattern: new RegExp("^/api/agents/config/notifications/test/?$"),
    params: [],
    module: route017 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/actions",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/actions/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route019 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/claude-transcript",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/claude-transcript/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route020 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/compact",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/compact/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route021 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/continue",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/continue/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route022 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/diffs",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/diffs/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route023 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/events-log",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/events-log/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route024 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/events",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/events/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route025 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/library/[slug]/add",
    pattern: new RegExp("^/api/agents/library/([^/]+)/add/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    module: route035 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/personas/[slug]/avatar",
    pattern: new RegExp("^/api/agents/personas/([^/]+)/avatar/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    module: route037 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/personas/[slug]/export",
    pattern: new RegExp("^/api/agents/personas/([^/]+)/export/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    module: route038 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/personas/[slug]/workspace",
    pattern: new RegExp("^/api/agents/personas/([^/]+)/workspace/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    module: route040 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/providers/[id]/models",
    pattern: new RegExp("^/api/agents/providers/([^/]+)/models/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route042 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/providers/[id]/verify",
    pattern: new RegExp("^/api/agents/providers/([^/]+)/verify/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route043 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills/[key]/bundle-into-cabinet",
    pattern: new RegExp("^/api/agents/skills/([^/]+)/bundle-into-cabinet/?$"),
    params: [{"name":"key","catchAll":false,"optional":false}],
    module: route049 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/daemon/session/[id]/output",
    pattern: new RegExp("^/api/daemon/session/([^/]+)/output/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route069 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/cabinet-env",
    pattern: new RegExp("^/api/agents/config/cabinet-env/?$"),
    params: [],
    module: route006 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/cli-mcp-servers",
    pattern: new RegExp("^/api/agents/config/cli-mcp-servers/?$"),
    params: [],
    module: route007 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/integration-environments",
    pattern: new RegExp("^/api/agents/config/integration-environments/?$"),
    params: [],
    module: route008 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/integrations",
    pattern: new RegExp("^/api/agents/config/integrations/?$"),
    params: [],
    module: route009 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/?$"),
    params: [],
    module: route014 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/events",
    pattern: new RegExp("^/api/agents/conversations/events/?$"),
    params: [],
    module: route027 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/providers/status",
    pattern: new RegExp("^/api/agents/providers/status/?$"),
    params: [],
    module: route045 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills/catalog",
    pattern: new RegExp("^/api/agents/skills/catalog/?$"),
    params: [],
    module: route051 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills/import",
    pattern: new RegExp("^/api/agents/skills/import/?$"),
    params: [],
    module: route052 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills/scan",
    pattern: new RegExp("^/api/agents/skills/scan/?$"),
    params: [],
    module: route054 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/kb/pages/meta",
    pattern: new RegExp("^/api/kb/pages/meta/?$"),
    params: [],
    module: route100 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/diagnostics/export",
    pattern: new RegExp("^/api/system/diagnostics/export/?$"),
    params: [],
    module: route120 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/diagnostics/log-tail",
    pattern: new RegExp("^/api/system/diagnostics/log-tail/?$"),
    params: [],
    module: route121 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/update/apply",
    pattern: new RegExp("^/api/system/update/apply/?$"),
    params: [],
    module: route137 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/update/status",
    pattern: new RegExp("^/api/system/update/status/?$"),
    params: [],
    module: route139 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/[id]/jobs/[jobId]",
    pattern: new RegExp("^/api/agents/([^/]+)/jobs/([^/]+)/?$"),
    params: [{"name":"id","catchAll":false,"optional":false},{"name":"jobId","catchAll":false,"optional":false}],
    module: route000 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/[id]/jobs",
    pattern: new RegExp("^/api/agents/([^/]+)/jobs/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route001 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/claude-login/[action]",
    pattern: new RegExp("^/api/agents/claude-login/([^/]+)/?$"),
    params: [{"name":"action","catchAll":false,"optional":false}],
    module: route005 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route026 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/personas/[slug]",
    pattern: new RegExp("^/api/agents/personas/([^/]+)/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    module: route039 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills/[key]",
    pattern: new RegExp("^/api/agents/skills/([^/]+)/?$"),
    params: [{"name":"key","catchAll":false,"optional":false}],
    module: route050 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/chat/channels/[slug]",
    pattern: new RegExp("^/api/chat/channels/([^/]+)/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    module: route065 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/git/diff/[hash]",
    pattern: new RegExp("^/api/git/diff/([^/]+)/?$"),
    params: [{"name":"hash","catchAll":false,"optional":false}],
    module: route074 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/thread/[id]",
    pattern: new RegExp("^/api/gmail/thread/([^/]+)/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route084 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/mounts/[id]",
    pattern: new RegExp("^/api/google-drive/mounts/([^/]+)/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route086 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/auto-link",
    pattern: new RegExp("^/api/agents/auto-link/?$"),
    params: [],
    module: route003 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/channels",
    pattern: new RegExp("^/api/agents/channels/?$"),
    params: [],
    module: route004 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config",
    pattern: new RegExp("^/api/agents/config/?$"),
    params: [],
    module: route018 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations",
    pattern: new RegExp("^/api/agents/conversations/?$"),
    params: [],
    module: route028 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/digest",
    pattern: new RegExp("^/api/agents/digest/?$"),
    params: [],
    module: route029 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/events",
    pattern: new RegExp("^/api/agents/events/?$"),
    params: [],
    module: route030 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/gallery",
    pattern: new RegExp("^/api/agents/gallery/?$"),
    params: [],
    module: route031 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/headless",
    pattern: new RegExp("^/api/agents/headless/?$"),
    params: [],
    module: route032 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/import",
    pattern: new RegExp("^/api/agents/import/?$"),
    params: [],
    module: route033 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/inbox-drafts",
    pattern: new RegExp("^/api/agents/inbox-drafts/?$"),
    params: [],
    module: route034 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/library",
    pattern: new RegExp("^/api/agents/library/?$"),
    params: [],
    module: route036 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/personas",
    pattern: new RegExp("^/api/agents/personas/?$"),
    params: [],
    module: route041 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/providers",
    pattern: new RegExp("^/api/agents/providers/?$"),
    params: [],
    module: route044 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/review",
    pattern: new RegExp("^/api/agents/review/?$"),
    params: [],
    module: route046 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/scheduler",
    pattern: new RegExp("^/api/agents/scheduler/?$"),
    params: [],
    module: route048 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills",
    pattern: new RegExp("^/api/agents/skills/?$"),
    params: [],
    module: route053 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/tasks",
    pattern: new RegExp("^/api/agents/tasks/?$"),
    params: [],
    module: route055 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/ai/render-md",
    pattern: new RegExp("^/api/ai/render-md/?$"),
    params: [],
    module: route056 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/auth/check",
    pattern: new RegExp("^/api/auth/check/?$"),
    params: [],
    module: route058 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/auth/login",
    pattern: new RegExp("^/api/auth/login/?$"),
    params: [],
    module: route059 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/browser/bookmarks",
    pattern: new RegExp("^/api/browser/bookmarks/?$"),
    params: [],
    module: route060 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/browser/frame-check",
    pattern: new RegExp("^/api/browser/frame-check/?$"),
    params: [],
    module: route061 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/cabinets/classify",
    pattern: new RegExp("^/api/cabinets/classify/?$"),
    params: [],
    module: route062 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/cabinets/create",
    pattern: new RegExp("^/api/cabinets/create/?$"),
    params: [],
    module: route063 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/cabinets/overview",
    pattern: new RegExp("^/api/cabinets/overview/?$"),
    params: [],
    module: route064 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/chat/channels",
    pattern: new RegExp("^/api/chat/channels/?$"),
    params: [],
    module: route066 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/cloud/status",
    pattern: new RegExp("^/api/cloud/status/?$"),
    params: [],
    module: route067 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/daemon/auth",
    pattern: new RegExp("^/api/daemon/auth/?$"),
    params: [],
    module: route068 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/daemon/sessions",
    pattern: new RegExp("^/api/daemon/sessions/?$"),
    params: [],
    module: route070 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/git/commit",
    pattern: new RegExp("^/api/git/commit/?$"),
    params: [],
    module: route073 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/git/pull",
    pattern: new RegExp("^/api/git/pull/?$"),
    params: [],
    module: route076 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/git/restore",
    pattern: new RegExp("^/api/git/restore/?$"),
    params: [],
    module: route077 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/github/repo",
    pattern: new RegExp("^/api/github/repo/?$"),
    params: [],
    module: route078 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/connect",
    pattern: new RegExp("^/api/gmail/connect/?$"),
    params: [],
    module: route079 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/disconnect",
    pattern: new RegExp("^/api/gmail/disconnect/?$"),
    params: [],
    module: route080 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/index",
    pattern: new RegExp("^/api/gmail/index/?$"),
    params: [],
    module: route081 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/search",
    pattern: new RegExp("^/api/gmail/search/?$"),
    params: [],
    module: route082 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/status",
    pattern: new RegExp("^/api/gmail/status/?$"),
    params: [],
    module: route083 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/browse",
    pattern: new RegExp("^/api/google-drive/browse/?$"),
    params: [],
    module: route085 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/mounts",
    pattern: new RegExp("^/api/google-drive/mounts/?$"),
    params: [],
    module: route087 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/reveal",
    pattern: new RegExp("^/api/google-drive/reveal/?$"),
    params: [],
    module: route088 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/serve",
    pattern: new RegExp("^/api/google-drive/serve/?$"),
    params: [],
    module: route089 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/status",
    pattern: new RegExp("^/api/google-drive/status/?$"),
    params: [],
    module: route090 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/tree",
    pattern: new RegExp("^/api/google-drive/tree/?$"),
    params: [],
    module: route091 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/health/daemon",
    pattern: new RegExp("^/api/health/daemon/?$"),
    params: [],
    module: route092 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/history/activity",
    pattern: new RegExp("^/api/history/activity/?$"),
    params: [],
    module: route094 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/history/compact",
    pattern: new RegExp("^/api/history/compact/?$"),
    params: [],
    module: route095 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/history/config",
    pattern: new RegExp("^/api/history/config/?$"),
    params: [],
    module: route096 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/history/diff",
    pattern: new RegExp("^/api/history/diff/?$"),
    params: [],
    module: route097 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/history/file",
    pattern: new RegExp("^/api/history/file/?$"),
    params: [],
    module: route098 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/jobs/library",
    pattern: new RegExp("^/api/jobs/library/?$"),
    params: [],
    module: route099 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/knowledge-sources/connect-inline",
    pattern: new RegExp("^/api/knowledge-sources/connect-inline/?$"),
    params: [],
    module: route101 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/knowledge-sources/scan",
    pattern: new RegExp("^/api/knowledge-sources/scan/?$"),
    params: [],
    module: route102 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/onboarding/setup",
    pattern: new RegExp("^/api/onboarding/setup/?$"),
    params: [],
    module: route103 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/references/undo",
    pattern: new RegExp("^/api/references/undo/?$"),
    params: [],
    module: route106 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/registry/import",
    pattern: new RegExp("^/api/registry/import/?$"),
    params: [],
    module: route108 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/rooms/active",
    pattern: new RegExp("^/api/rooms/active/?$"),
    params: [],
    module: route110 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/schedule/parse",
    pattern: new RegExp("^/api/schedule/parse/?$"),
    params: [],
    module: route112 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/audit-log",
    pattern: new RegExp("^/api/system/audit-log/?$"),
    params: [],
    module: route114 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/backup",
    pattern: new RegExp("^/api/system/backup/?$"),
    params: [],
    module: route115 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/cabinet-manifest",
    pattern: new RegExp("^/api/system/cabinet-manifest/?$"),
    params: [],
    module: route116 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/client-log",
    pattern: new RegExp("^/api/system/client-log/?$"),
    params: [],
    module: route117 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/create-file",
    pattern: new RegExp("^/api/system/create-file/?$"),
    params: [],
    module: route118 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/data-dir",
    pattern: new RegExp("^/api/system/data-dir/?$"),
    params: [],
    module: route119 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/diagnostics",
    pattern: new RegExp("^/api/system/diagnostics/?$"),
    params: [],
    module: route122 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/feedback",
    pattern: new RegExp("^/api/system/feedback/?$"),
    params: [],
    module: route123 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/file-settings",
    pattern: new RegExp("^/api/system/file-settings/?$"),
    params: [],
    module: route124 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/import-apple-notes",
    pattern: new RegExp("^/api/system/import-apple-notes/?$"),
    params: [],
    module: route125 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/import-folder",
    pattern: new RegExp("^/api/system/import-folder/?$"),
    params: [],
    module: route126 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/import-notion",
    pattern: new RegExp("^/api/system/import-notion/?$"),
    params: [],
    module: route127 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/integration-requests",
    pattern: new RegExp("^/api/system/integration-requests/?$"),
    params: [],
    module: route128 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/link-repo",
    pattern: new RegExp("^/api/system/link-repo/?$"),
    params: [],
    module: route129 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/open-data-dir",
    pattern: new RegExp("^/api/system/open-data-dir/?$"),
    params: [],
    module: route130 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/open-path",
    pattern: new RegExp("^/api/system/open-path/?$"),
    params: [],
    module: route131 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/pick-directory",
    pattern: new RegExp("^/api/system/pick-directory/?$"),
    params: [],
    module: route132 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/pick-file",
    pattern: new RegExp("^/api/system/pick-file/?$"),
    params: [],
    module: route133 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/restart",
    pattern: new RegExp("^/api/system/restart/?$"),
    params: [],
    module: route134 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/reveal",
    pattern: new RegExp("^/api/system/reveal/?$"),
    params: [],
    module: route135 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/symlink",
    pattern: new RegExp("^/api/system/symlink/?$"),
    params: [],
    module: route136 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/update",
    pattern: new RegExp("^/api/system/update/?$"),
    params: [],
    module: route138 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/telemetry/settings",
    pattern: new RegExp("^/api/telemetry/settings/?$"),
    params: [],
    module: route141 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/terminal/open",
    pattern: new RegExp("^/api/terminal/open/?$"),
    params: [],
    module: route142 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/user/avatar",
    pattern: new RegExp("^/api/user/avatar/?$"),
    params: [],
    module: route145 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/user/profile",
    pattern: new RegExp("^/api/user/profile/?$"),
    params: [],
    module: route146 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/git/log/[...path]",
    pattern: new RegExp("^/api/git/log/(.+)/?$"),
    params: [{"name":"path","catchAll":true,"optional":false}],
    module: route075 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/[id]",
    pattern: new RegExp("^/api/agents/([^/]+)/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    module: route002 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/registry/[slug]",
    pattern: new RegExp("^/api/registry/([^/]+)/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    module: route107 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents",
    pattern: new RegExp("^/api/agents/?$"),
    params: [],
    module: route047 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/data-locations",
    pattern: new RegExp("^/api/data-locations/?$"),
    params: [],
    module: route071 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/disclaimer",
    pattern: new RegExp("^/api/disclaimer/?$"),
    params: [],
    module: route072 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/health",
    pattern: new RegExp("^/api/health/?$"),
    params: [],
    module: route093 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/pages",
    pattern: new RegExp("^/api/pages/?$"),
    params: [],
    module: route105 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/registry",
    pattern: new RegExp("^/api/registry/?$"),
    params: [],
    module: route109 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/rooms",
    pattern: new RegExp("^/api/rooms/?$"),
    params: [],
    module: route111 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/search",
    pattern: new RegExp("^/api/search/?$"),
    params: [],
    module: route113 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/telemetry",
    pattern: new RegExp("^/api/telemetry/?$"),
    params: [],
    module: route140 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/tree",
    pattern: new RegExp("^/api/tree/?$"),
    params: [],
    module: route143 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/assets/[...path]",
    pattern: new RegExp("^/api/assets/(.+)/?$"),
    params: [{"name":"path","catchAll":true,"optional":false}],
    module: route057 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/pages/[...path]",
    pattern: new RegExp("^/api/pages/(.+)/?$"),
    params: [{"name":"path","catchAll":true,"optional":false}],
    module: route104 as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/upload/[...path]",
    pattern: new RegExp("^/api/upload/(.+)/?$"),
    params: [{"name":"path","catchAll":true,"optional":false}],
    module: route144 as unknown as CloudRouteModule,
  },
];

export function matchCloudRoute(pathname: string): {
  pathname: string;
  module: CloudRouteModule;
  params: Record<string, string | string[]>;
} | null {
  for (const route of routes) {
    const match = route.pattern.exec(pathname);
    if (!match) continue;
    const params: Record<string, string | string[]> = {};
    route.params.forEach((parameter, index) => {
      const raw = match[index + 1] || "";
      if (parameter.catchAll) {
        params[parameter.name] = raw
          ? raw.split("/").filter(Boolean).map((part) => decodeURIComponent(part))
          : [];
      } else if (raw || !parameter.optional) {
        params[parameter.name] = decodeURIComponent(raw);
      }
    });
    return { pathname: route.pathname, module: route.module, params };
  }
  return null;
}
