/* eslint-disable */
// Generated by scripts/generate-cloud-route-manifest.mjs. Do not edit by hand.
import type { NextRequest } from "next/server";

export type CloudRouteMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";
export type CloudRouteHandler = (
  request: NextRequest,
  context: { params: Promise<Record<string, string | string[]>> }
) => Response | Promise<Response>;
export type CloudRouteModule = Partial<Record<CloudRouteMethod, CloudRouteHandler>>;

interface CloudRouteEntry {
  pathname: string;
  pattern: RegExp;
  params: Array<{ name: string; catchAll: boolean; optional: boolean }>;
  load: () => Promise<CloudRouteModule>;
}

const routes: CloudRouteEntry[] = [
  {
    pathname: "/api/agents/config/mcp-catalog/microsoft/login",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/microsoft/login/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/mcp-catalog/microsoft/login/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog/oauth/login",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/oauth/login/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/mcp-catalog/oauth/login/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog/connect",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/connect/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/mcp-catalog/connect/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog/discord-check",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/discord-check/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/mcp-catalog/discord-check/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog/test",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/test/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/mcp-catalog/test/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog/verify",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/verify/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/mcp-catalog/verify/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/notifications/test",
    pattern: new RegExp("^/api/agents/config/notifications/test/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/notifications/test/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/actions",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/actions/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/conversations/[id]/actions/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/claude-transcript",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/claude-transcript/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/conversations/[id]/claude-transcript/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/compact",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/compact/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/conversations/[id]/compact/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/continue",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/continue/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/conversations/[id]/continue/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/diffs",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/diffs/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/conversations/[id]/diffs/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/events-log",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/events-log/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/conversations/[id]/events-log/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]/events",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/events/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/conversations/[id]/events/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/library/[slug]/add",
    pattern: new RegExp("^/api/agents/library/([^/]+)/add/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/library/[slug]/add/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/personas/[slug]/avatar",
    pattern: new RegExp("^/api/agents/personas/([^/]+)/avatar/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/personas/[slug]/avatar/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/personas/[slug]/export",
    pattern: new RegExp("^/api/agents/personas/([^/]+)/export/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/personas/[slug]/export/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/personas/[slug]/workspace",
    pattern: new RegExp("^/api/agents/personas/([^/]+)/workspace/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/personas/[slug]/workspace/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/providers/[id]/models",
    pattern: new RegExp("^/api/agents/providers/([^/]+)/models/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/providers/[id]/models/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/providers/[id]/verify",
    pattern: new RegExp("^/api/agents/providers/([^/]+)/verify/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/providers/[id]/verify/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills/[key]/bundle-into-cabinet",
    pattern: new RegExp("^/api/agents/skills/([^/]+)/bundle-into-cabinet/?$"),
    params: [{"name":"key","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/skills/[key]/bundle-into-cabinet/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/daemon/session/[id]/output",
    pattern: new RegExp("^/api/daemon/session/([^/]+)/output/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/daemon/session/[id]/output/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/cabinet-env",
    pattern: new RegExp("^/api/agents/config/cabinet-env/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/cabinet-env/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/cli-mcp-servers",
    pattern: new RegExp("^/api/agents/config/cli-mcp-servers/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/cli-mcp-servers/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/integration-environments",
    pattern: new RegExp("^/api/agents/config/integration-environments/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/integration-environments/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/integrations",
    pattern: new RegExp("^/api/agents/config/integrations/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/integrations/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config/mcp-catalog",
    pattern: new RegExp("^/api/agents/config/mcp-catalog/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/mcp-catalog/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/events",
    pattern: new RegExp("^/api/agents/conversations/events/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/conversations/events/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/providers/status",
    pattern: new RegExp("^/api/agents/providers/status/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/providers/status/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills/catalog",
    pattern: new RegExp("^/api/agents/skills/catalog/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/skills/catalog/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills/import",
    pattern: new RegExp("^/api/agents/skills/import/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/skills/import/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills/scan",
    pattern: new RegExp("^/api/agents/skills/scan/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/skills/scan/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/kb/pages/meta",
    pattern: new RegExp("^/api/kb/pages/meta/?$"),
    params: [],
    load: async () => (await import("@/app/api/kb/pages/meta/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/diagnostics/export",
    pattern: new RegExp("^/api/system/diagnostics/export/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/diagnostics/export/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/diagnostics/log-tail",
    pattern: new RegExp("^/api/system/diagnostics/log-tail/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/diagnostics/log-tail/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/update/apply",
    pattern: new RegExp("^/api/system/update/apply/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/update/apply/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/update/status",
    pattern: new RegExp("^/api/system/update/status/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/update/status/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/[id]/jobs/[jobId]",
    pattern: new RegExp("^/api/agents/([^/]+)/jobs/([^/]+)/?$"),
    params: [{"name":"id","catchAll":false,"optional":false},{"name":"jobId","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/[id]/jobs/[jobId]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/[id]/jobs",
    pattern: new RegExp("^/api/agents/([^/]+)/jobs/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/[id]/jobs/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/claude-login/[action]",
    pattern: new RegExp("^/api/agents/claude-login/([^/]+)/?$"),
    params: [{"name":"action","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/claude-login/[action]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations/[id]",
    pattern: new RegExp("^/api/agents/conversations/([^/]+)/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/conversations/[id]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/personas/[slug]",
    pattern: new RegExp("^/api/agents/personas/([^/]+)/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/personas/[slug]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills/[key]",
    pattern: new RegExp("^/api/agents/skills/([^/]+)/?$"),
    params: [{"name":"key","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/skills/[key]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/chat/channels/[slug]",
    pattern: new RegExp("^/api/chat/channels/([^/]+)/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/chat/channels/[slug]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/git/diff/[hash]",
    pattern: new RegExp("^/api/git/diff/([^/]+)/?$"),
    params: [{"name":"hash","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/git/diff/[hash]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/thread/[id]",
    pattern: new RegExp("^/api/gmail/thread/([^/]+)/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/gmail/thread/[id]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/mounts/[id]",
    pattern: new RegExp("^/api/google-drive/mounts/([^/]+)/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/google-drive/mounts/[id]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/auto-link",
    pattern: new RegExp("^/api/agents/auto-link/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/auto-link/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/channels",
    pattern: new RegExp("^/api/agents/channels/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/channels/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/config",
    pattern: new RegExp("^/api/agents/config/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/config/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/conversations",
    pattern: new RegExp("^/api/agents/conversations/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/conversations/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/digest",
    pattern: new RegExp("^/api/agents/digest/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/digest/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/events",
    pattern: new RegExp("^/api/agents/events/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/events/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/gallery",
    pattern: new RegExp("^/api/agents/gallery/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/gallery/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/headless",
    pattern: new RegExp("^/api/agents/headless/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/headless/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/import",
    pattern: new RegExp("^/api/agents/import/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/import/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/inbox-drafts",
    pattern: new RegExp("^/api/agents/inbox-drafts/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/inbox-drafts/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/library",
    pattern: new RegExp("^/api/agents/library/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/library/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/personas",
    pattern: new RegExp("^/api/agents/personas/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/personas/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/providers",
    pattern: new RegExp("^/api/agents/providers/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/providers/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/review",
    pattern: new RegExp("^/api/agents/review/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/review/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/scheduler",
    pattern: new RegExp("^/api/agents/scheduler/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/scheduler/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/skills",
    pattern: new RegExp("^/api/agents/skills/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/skills/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/tasks",
    pattern: new RegExp("^/api/agents/tasks/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/tasks/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/ai/render-md",
    pattern: new RegExp("^/api/ai/render-md/?$"),
    params: [],
    load: async () => (await import("@/app/api/ai/render-md/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/auth/check",
    pattern: new RegExp("^/api/auth/check/?$"),
    params: [],
    load: async () => (await import("@/app/api/auth/check/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/auth/login",
    pattern: new RegExp("^/api/auth/login/?$"),
    params: [],
    load: async () => (await import("@/app/api/auth/login/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/browser/bookmarks",
    pattern: new RegExp("^/api/browser/bookmarks/?$"),
    params: [],
    load: async () => (await import("@/app/api/browser/bookmarks/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/browser/frame-check",
    pattern: new RegExp("^/api/browser/frame-check/?$"),
    params: [],
    load: async () => (await import("@/app/api/browser/frame-check/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/cabinets/classify",
    pattern: new RegExp("^/api/cabinets/classify/?$"),
    params: [],
    load: async () => (await import("@/app/api/cabinets/classify/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/cabinets/create",
    pattern: new RegExp("^/api/cabinets/create/?$"),
    params: [],
    load: async () => (await import("@/app/api/cabinets/create/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/cabinets/overview",
    pattern: new RegExp("^/api/cabinets/overview/?$"),
    params: [],
    load: async () => (await import("@/app/api/cabinets/overview/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/chat/channels",
    pattern: new RegExp("^/api/chat/channels/?$"),
    params: [],
    load: async () => (await import("@/app/api/chat/channels/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/cloud/status",
    pattern: new RegExp("^/api/cloud/status/?$"),
    params: [],
    load: async () => (await import("@/app/api/cloud/status/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/daemon/auth",
    pattern: new RegExp("^/api/daemon/auth/?$"),
    params: [],
    load: async () => (await import("@/app/api/daemon/auth/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/daemon/sessions",
    pattern: new RegExp("^/api/daemon/sessions/?$"),
    params: [],
    load: async () => (await import("@/app/api/daemon/sessions/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/git/commit",
    pattern: new RegExp("^/api/git/commit/?$"),
    params: [],
    load: async () => (await import("@/app/api/git/commit/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/git/pull",
    pattern: new RegExp("^/api/git/pull/?$"),
    params: [],
    load: async () => (await import("@/app/api/git/pull/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/git/restore",
    pattern: new RegExp("^/api/git/restore/?$"),
    params: [],
    load: async () => (await import("@/app/api/git/restore/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/github/repo",
    pattern: new RegExp("^/api/github/repo/?$"),
    params: [],
    load: async () => (await import("@/app/api/github/repo/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/connect",
    pattern: new RegExp("^/api/gmail/connect/?$"),
    params: [],
    load: async () => (await import("@/app/api/gmail/connect/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/disconnect",
    pattern: new RegExp("^/api/gmail/disconnect/?$"),
    params: [],
    load: async () => (await import("@/app/api/gmail/disconnect/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/index",
    pattern: new RegExp("^/api/gmail/index/?$"),
    params: [],
    load: async () => (await import("@/app/api/gmail/index/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/search",
    pattern: new RegExp("^/api/gmail/search/?$"),
    params: [],
    load: async () => (await import("@/app/api/gmail/search/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/gmail/status",
    pattern: new RegExp("^/api/gmail/status/?$"),
    params: [],
    load: async () => (await import("@/app/api/gmail/status/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/browse",
    pattern: new RegExp("^/api/google-drive/browse/?$"),
    params: [],
    load: async () => (await import("@/app/api/google-drive/browse/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/mounts",
    pattern: new RegExp("^/api/google-drive/mounts/?$"),
    params: [],
    load: async () => (await import("@/app/api/google-drive/mounts/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/reveal",
    pattern: new RegExp("^/api/google-drive/reveal/?$"),
    params: [],
    load: async () => (await import("@/app/api/google-drive/reveal/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/serve",
    pattern: new RegExp("^/api/google-drive/serve/?$"),
    params: [],
    load: async () => (await import("@/app/api/google-drive/serve/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/status",
    pattern: new RegExp("^/api/google-drive/status/?$"),
    params: [],
    load: async () => (await import("@/app/api/google-drive/status/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/google-drive/tree",
    pattern: new RegExp("^/api/google-drive/tree/?$"),
    params: [],
    load: async () => (await import("@/app/api/google-drive/tree/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/health/daemon",
    pattern: new RegExp("^/api/health/daemon/?$"),
    params: [],
    load: async () => (await import("@/app/api/health/daemon/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/history/activity",
    pattern: new RegExp("^/api/history/activity/?$"),
    params: [],
    load: async () => (await import("@/app/api/history/activity/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/history/compact",
    pattern: new RegExp("^/api/history/compact/?$"),
    params: [],
    load: async () => (await import("@/app/api/history/compact/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/history/config",
    pattern: new RegExp("^/api/history/config/?$"),
    params: [],
    load: async () => (await import("@/app/api/history/config/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/history/diff",
    pattern: new RegExp("^/api/history/diff/?$"),
    params: [],
    load: async () => (await import("@/app/api/history/diff/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/history/file",
    pattern: new RegExp("^/api/history/file/?$"),
    params: [],
    load: async () => (await import("@/app/api/history/file/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/jobs/library",
    pattern: new RegExp("^/api/jobs/library/?$"),
    params: [],
    load: async () => (await import("@/app/api/jobs/library/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/knowledge-sources/connect-inline",
    pattern: new RegExp("^/api/knowledge-sources/connect-inline/?$"),
    params: [],
    load: async () => (await import("@/app/api/knowledge-sources/connect-inline/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/knowledge-sources/scan",
    pattern: new RegExp("^/api/knowledge-sources/scan/?$"),
    params: [],
    load: async () => (await import("@/app/api/knowledge-sources/scan/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/onboarding/setup",
    pattern: new RegExp("^/api/onboarding/setup/?$"),
    params: [],
    load: async () => (await import("@/app/api/onboarding/setup/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/references/undo",
    pattern: new RegExp("^/api/references/undo/?$"),
    params: [],
    load: async () => (await import("@/app/api/references/undo/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/registry/import",
    pattern: new RegExp("^/api/registry/import/?$"),
    params: [],
    load: async () => (await import("@/app/api/registry/import/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/rooms/active",
    pattern: new RegExp("^/api/rooms/active/?$"),
    params: [],
    load: async () => (await import("@/app/api/rooms/active/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/schedule/parse",
    pattern: new RegExp("^/api/schedule/parse/?$"),
    params: [],
    load: async () => (await import("@/app/api/schedule/parse/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/audit-log",
    pattern: new RegExp("^/api/system/audit-log/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/audit-log/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/backup",
    pattern: new RegExp("^/api/system/backup/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/backup/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/cabinet-manifest",
    pattern: new RegExp("^/api/system/cabinet-manifest/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/cabinet-manifest/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/client-log",
    pattern: new RegExp("^/api/system/client-log/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/client-log/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/create-file",
    pattern: new RegExp("^/api/system/create-file/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/create-file/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/data-dir",
    pattern: new RegExp("^/api/system/data-dir/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/data-dir/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/diagnostics",
    pattern: new RegExp("^/api/system/diagnostics/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/diagnostics/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/feedback",
    pattern: new RegExp("^/api/system/feedback/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/feedback/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/file-settings",
    pattern: new RegExp("^/api/system/file-settings/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/file-settings/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/import-apple-notes",
    pattern: new RegExp("^/api/system/import-apple-notes/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/import-apple-notes/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/import-folder",
    pattern: new RegExp("^/api/system/import-folder/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/import-folder/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/import-notion",
    pattern: new RegExp("^/api/system/import-notion/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/import-notion/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/integration-requests",
    pattern: new RegExp("^/api/system/integration-requests/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/integration-requests/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/link-repo",
    pattern: new RegExp("^/api/system/link-repo/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/link-repo/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/open-data-dir",
    pattern: new RegExp("^/api/system/open-data-dir/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/open-data-dir/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/open-path",
    pattern: new RegExp("^/api/system/open-path/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/open-path/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/pick-directory",
    pattern: new RegExp("^/api/system/pick-directory/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/pick-directory/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/pick-file",
    pattern: new RegExp("^/api/system/pick-file/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/pick-file/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/restart",
    pattern: new RegExp("^/api/system/restart/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/restart/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/reveal",
    pattern: new RegExp("^/api/system/reveal/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/reveal/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/symlink",
    pattern: new RegExp("^/api/system/symlink/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/symlink/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/system/update",
    pattern: new RegExp("^/api/system/update/?$"),
    params: [],
    load: async () => (await import("@/app/api/system/update/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/telemetry/settings",
    pattern: new RegExp("^/api/telemetry/settings/?$"),
    params: [],
    load: async () => (await import("@/app/api/telemetry/settings/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/terminal/open",
    pattern: new RegExp("^/api/terminal/open/?$"),
    params: [],
    load: async () => (await import("@/app/api/terminal/open/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/user/avatar",
    pattern: new RegExp("^/api/user/avatar/?$"),
    params: [],
    load: async () => (await import("@/app/api/user/avatar/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/user/profile",
    pattern: new RegExp("^/api/user/profile/?$"),
    params: [],
    load: async () => (await import("@/app/api/user/profile/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/git/log/[...path]",
    pattern: new RegExp("^/api/git/log/(.+)/?$"),
    params: [{"name":"path","catchAll":true,"optional":false}],
    load: async () => (await import("@/app/api/git/log/[...path]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents/[id]",
    pattern: new RegExp("^/api/agents/([^/]+)/?$"),
    params: [{"name":"id","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/agents/[id]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/registry/[slug]",
    pattern: new RegExp("^/api/registry/([^/]+)/?$"),
    params: [{"name":"slug","catchAll":false,"optional":false}],
    load: async () => (await import("@/app/api/registry/[slug]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/agents",
    pattern: new RegExp("^/api/agents/?$"),
    params: [],
    load: async () => (await import("@/app/api/agents/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/data-locations",
    pattern: new RegExp("^/api/data-locations/?$"),
    params: [],
    load: async () => (await import("@/app/api/data-locations/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/disclaimer",
    pattern: new RegExp("^/api/disclaimer/?$"),
    params: [],
    load: async () => (await import("@/app/api/disclaimer/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/health",
    pattern: new RegExp("^/api/health/?$"),
    params: [],
    load: async () => (await import("@/app/api/health/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/pages",
    pattern: new RegExp("^/api/pages/?$"),
    params: [],
    load: async () => (await import("@/app/api/pages/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/registry",
    pattern: new RegExp("^/api/registry/?$"),
    params: [],
    load: async () => (await import("@/app/api/registry/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/rooms",
    pattern: new RegExp("^/api/rooms/?$"),
    params: [],
    load: async () => (await import("@/app/api/rooms/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/search",
    pattern: new RegExp("^/api/search/?$"),
    params: [],
    load: async () => (await import("@/app/api/search/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/telemetry",
    pattern: new RegExp("^/api/telemetry/?$"),
    params: [],
    load: async () => (await import("@/app/api/telemetry/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/tree",
    pattern: new RegExp("^/api/tree/?$"),
    params: [],
    load: async () => (await import("@/app/api/tree/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/assets/[...path]",
    pattern: new RegExp("^/api/assets/(.+)/?$"),
    params: [{"name":"path","catchAll":true,"optional":false}],
    load: async () => (await import("@/app/api/assets/[...path]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/pages/[...path]",
    pattern: new RegExp("^/api/pages/(.+)/?$"),
    params: [{"name":"path","catchAll":true,"optional":false}],
    load: async () => (await import("@/app/api/pages/[...path]/route")) as unknown as CloudRouteModule,
  },
  {
    pathname: "/api/upload/[...path]",
    pattern: new RegExp("^/api/upload/(.+)/?$"),
    params: [{"name":"path","catchAll":true,"optional":false}],
    load: async () => (await import("@/app/api/upload/[...path]/route")) as unknown as CloudRouteModule,
  },
];

export function matchCloudRoute(pathname: string): {
  pathname: string;
  load: () => Promise<CloudRouteModule>;
  params: Record<string, string | string[]>;
} | null {
  for (const route of routes) {
    const match = route.pattern.exec(pathname);
    if (!match) continue;
    const params: Record<string, string | string[]> = {};
    route.params.forEach((parameter, index) => {
      const raw = match[index + 1] || "";
      if (parameter.catchAll) {
        params[parameter.name] = raw
          ? raw.split("/").filter(Boolean).map((part) => decodeURIComponent(part))
          : [];
      } else if (raw || !parameter.optional) {
        params[parameter.name] = decodeURIComponent(raw);
      }
    });
    return { pathname: route.pathname, load: route.load, params };
  }
  return null;
}
